[build]
  command = "npm run build"

  functions = "functions/"

  publish = "public/"
  
[build.environment]
  # Fix to ensure the Prisma binary is packaged with the lambda function
  ZISI_VERSION = "0.4.0-9"
